### PR TITLE
Done

### PR DESCRIPTION
**Pull request by jakebrady5**

### CODE REVIEW

**Comment by aturkewi** [comment]
@jakebrady5 I took a look at your tests for this and I'm not sure if they actually work. If you play around with changing the mocked data (but not changing the expected result) you'll see that the tests still pass. If you take another look at the lab and can't figure out why this is happening, ping me on here or on slack (i'm `avidor` on slack).

**Comment by jakebrady5** [comment]
Thanks, @aturkewi.  I'll check this out when I get home tonight.  It seems that the first test is the main offender?  The second doesn't use mocked data as I thought to isolate just that controller method.  I suppose I can change it up to use mocked request data as well though.  I'll ping you if I run into issues.

**Comment by aturkewi** [comment]
@jakebrady5 , you are correct. I should have been more specific, it is your first test that is an issues. Let me know how this works for you, and happy coding :)

**Comment by jakebrady5** [comment]
Could not get any results with passing done in through the initial function.  I was getting a timeout error.  I did get it working with a simple expect().toEqual, but feel like maybe that's the easy way out?

**Pull request closed without merging**
